### ISSUE TITLE
Sketch does not compile

### ISSUE THREAD

**Issue by circuito1984** [ElectronHacks/MQTT_ESP8266_Garage_Door#2]
When I try to compile the sketch, it shows this Error: 

GarageDoorOpener:31: error: 'callback' was not declared in this scope

PubSubClient client(server, 1883, callback, wifiClient);

I use arduino 1.6.11

any idea why?

Thank You

**Comment by jhottell** [comment]
Unfortunately this code only works with arduino IDE version 1.6.5 and older, after this there was a bug in the IDE that they don't plan to fix. A version of this code for the latest IDE is needed where the function prototype is created before it's referred to in the client object instantiation. Information here: http://forum.arduino.cc/index.php?topic=370284.0 I will try fix for the latest IDE soon. If you would like to do this yourself I suggest getting the latest IDE and look at the PubSub example and see how they instantiate the PubSub differently to make it work, you will see they put the callback in a different place.

**Comment by jhottell** [comment]
Fixed, see the new V2 version of the sketch for the latest Arduino IDE 1.6.13 but should work with all IDEs newer than 1.6.5
